import React from'react';

const Mypostedpicstorehere= [
    {postedpicsrc: "https://rukminim1.flixcart.com/image/352/352/jiyvvrk0/poster/r/h/d/large-rama-jai-shri-ram-poster-god-devotional-wall-poster-for-original-imaf67z3tew2gdr2.jpeg?q=70"},
    {postedpicsrc: "https://rukminim1.flixcart.com/image/352/352/k3j1z0w0/sticker/z/4/d/white-glossy-modern-art534-large-51-white-glossy-modern-art534-original-imafmjwygnffbdqf.jpeg?q=70"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyoFAuYmP_ME5QxrWmZt9AXp02-Nrn-tg-Rg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXDmkieWxczAGjmOyG6hv_QWo1YPGhHEzeXQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuMvj8s7t7EBW2OjF5ByWCfl_lRX9NcPJ6dQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPK9G8pmQMVcCV1XCFDHdpv-osXHMIj5yelg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWoTJ9CFnGc149vIihQkjw9SmckRRC8CSfyg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Dyei0EidMHVH8eDqUEgYr6kqo_Pp9RfI-w&usqp=CAU"},
    {postedpicsrc: "https://i0.wp.com/www.opindia.com/wp-content/uploads/2018/04/shree-Ram.jpg?fit=1200%2C630&ssl=1"},
    {postedpicsrc: "https://wallpapercave.com/wp/wp5902761.jpg"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo7MVrICgf2QGNjphMom7s1yVeOLuZGuABDg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpW7zEdbG-7C0UsoLFR_de1OUFos0UQFZuGg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTguBL0CXFnBkSTOv87Npd9nZ6Xlszz63BqiQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg7z8VsQmBjscgQOmnYAHyAEAtYYGK_jfaw&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFU0ArNUYibtpXw_xZg0TQh7984ZfsGUylTw&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuMvj8s7t7EBW2OjF5ByWCfl_lRX9NcPJ6dQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPK9G8pmQMVcCV1XCFDHdpv-osXHMIj5yelg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWoTJ9CFnGc149vIihQkjw9SmckRRC8CSfyg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Dyei0EidMHVH8eDqUEgYr6kqo_Pp9RfI-w&usqp=CAU"},
    {postedpicsrc: "https://i0.wp.com/www.opindia.com/wp-content/uploads/2018/04/shree-Ram.jpg?fit=1200%2C630&ssl=1"},
    {postedpicsrc: "https://wallpapercave.com/wp/wp5902761.jpg"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo7MVrICgf2QGNjphMom7s1yVeOLuZGuABDg&usqp=CAU"},
    {postedpicsrc: "https://rukminim1.flixcart.com/image/352/352/jiyvvrk0/poster/r/h/d/large-rama-jai-shri-ram-poster-god-devotional-wall-poster-for-original-imaf67z3tew2gdr2.jpeg?q=70"},
    {postedpicsrc: "https://rukminim1.flixcart.com/image/352/352/k3j1z0w0/sticker/z/4/d/white-glossy-modern-art534-large-51-white-glossy-modern-art534-original-imafmjwygnffbdqf.jpeg?q=70"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyoFAuYmP_ME5QxrWmZt9AXp02-Nrn-tg-Rg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXDmkieWxczAGjmOyG6hv_QWo1YPGhHEzeXQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuMvj8s7t7EBW2OjF5ByWCfl_lRX9NcPJ6dQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPK9G8pmQMVcCV1XCFDHdpv-osXHMIj5yelg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFU0ArNUYibtpXw_xZg0TQh7984ZfsGUylTw&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuMvj8s7t7EBW2OjF5ByWCfl_lRX9NcPJ6dQ&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPK9G8pmQMVcCV1XCFDHdpv-osXHMIj5yelg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWoTJ9CFnGc149vIihQkjw9SmckRRC8CSfyg&usqp=CAU"},
    {postedpicsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Dyei0EidMHVH8eDqUEgYr6kqo_Pp9RfI-w&usqp=CAU"},
    
];

export default Mypostedpicstorehere;